version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - echo "Build completed successfully."
  post_build:
    commands:
      - npm prune --production # Reduce image size

artifacts:
  files:
    - '**/*'
    - 'buildspec.yml' # Include the buildspec for debugging
